# MailExtractor
# Description : Extracts email addresses from html file
# Developed by : Malhar Vora
# Developed on : Oct 11 2012
# Email : mlvora.2010@gmail.com
# Web   : www.malhar2010.blogspot.com
# Web   : www.byteofcloud.blogspot.in
##################################################################

import sys
import re
import os

if len(sys.argv) <=2:
    print "Mail Extractor"  
    print "Version : 1.0"
    print "Usage : mailextractor outputfile htmlfile1 htmlfile2 htmlfile[n]"    
    print "Developed by Malhar Vora"
    print "Email : mlvora.2010@gmail.com"
    print "Web   : www.malhar2010.blogspot.com"
    print "Web   : www.byteofcloud.blogspot.in"
    print "==================================================="
    sys.exit(0)

'''Method to extract mails from htmlfile and write to outputfile'''
def extractMails(htmlfile, outputfile):
    found = list()
    mailregex = re.compile( r'\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b',re.IGNORECASE)
    for line in htmlfile:
        maillist = mailregex.findall(line)
        for mail in maillist:
            if mail.lower() not in found:
                outputfile.write(mail.lower() + "\n") # Write found mail to file 
                found.append(mail.lower())
    


emailfile = open(sys.argv[1], "w")

# Iterate through command line list, extract emails from files and write them to outputfile
for htmlfile in sys.argv[2:]:
    if os.path.exists(htmlfile):
        if os.path.isfile(htmlfile):
            print "Extracting data from " + htmlfile
            ofile = open(htmlfile, "r")
            extractMails(ofile, emailfile)
            ofile.close()
        else:
            print "File not found : " +  htmlfile
             
    else:
        print "File not found : " +  htmlfile

emailfile.write("\n\n\n=====================================\n")
emailfile.write("Generated by MailExtractor 1.0\n")
emailfile.write("Developed by Malhar Vora\n")
emailfile.write("=====================================\n")


emailfile.close()

print "Emails are written in " + sys.argv[1]   
